name: Publish Docker
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
env:
 LOGIN: ${{ secrets.DOCKER_LOGIN }}
 NAME: ${{ secrets.DOCKER_NAME }}
steps:
- name: Login to docker.io
 - uses: actions/checkout@master
 - name: Build image
   run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
 - name: Push image to docker.io
   run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
