name: Build and Publish Docker
on:
  push:
    branches:
      - master
jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }} 
    steps:
      - id: login
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - id: build
        run: sudo docker build -t $LOGIN/$NAME .
      - id: push
        run: docker pull $LOGIN/$NAME 
