name: Build and Publish Docker
on:
  push:
    branches:
      - master
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - id: login
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - id: build
        run: sudo docker build -t artemonishchuk/java .
      - id: push
        run: docker pull artemonishchuk/java 
